fix after first test
started organizing

diff --git a/nginx-hostname b/nginx-hostname
--- a/nginx-hostname
+++ b/nginx-hostname
@@ -1,45 +1,52 @@
+#!/usr/bin/env bash
+
+# sets app hostnames based on VHOST file,
+# located in app's repo root
+
 set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
 source "$(dirname $0)/../common/functions"
 
-# save stdout outlet
-exec 4<&1
+# save stdout outlet for latter
+  exec 4<&1
 
-# disable stdout / stderr
-exec 1>/dev/null
-exec 2>/dev/null
+# disable stdout & stderr
+  exec 1>/dev/null
+  exec 2>/dev/null
 
-[[ ! -f "$DOKKU_ROOT/$APP/CONTAINER" ]] && exit 0
-[[ ! -f "$DOKKU_ROOT/VHOST" ]] && exit 0
+# arguments
+  APP="$1"; SUBDOMAIN="$2"; VHOST="$3"
 
-APP="$1"; SUBDOMAIN="$2"; VHOST="$3"
+# error
+  [[ ! -f "$DOKKU_ROOT/$APP/CONTAINER" ]] && exit 0
+  [[ ! -f "$DOKKU_ROOT/VHOST" ]] && exit 0
 
-if [[ "$APP" == *.* ]] && [[ "$SUBDOMAIN" == "$APP" ]]; then
-  autohostname="${APP/\//-}"
-else
-  autohostname="${APP/\//-}.$VHOST"
-fi
+# variables
+  CONTAINERID="$(cat ${DOKKU_ROOT}/${APP}/CONTAINER)"
+  TMPDIR=$(mktemp -d /tmp/VHOST.XXXXX);
 
-CONTAINERID="$(cat ${DOKKU_ROOT}/${APP}/CONTAINER)"
-TMPDIR=$(mktemp -d /tmp/VHOST.XXXXX);
+# schedule cleanup
+  cleanup() {
+    rm -rf $TMPDIR 2> /dev/null || true;
+  }
+  trap cleanup EXIT
 
-docker cp $CONTAINERID:/app/VHOST $TMPDIR 2> /dev/null || true;
-cleanup() {
-  rm -rf $TMPDIR 2> /dev/null || true;
-}
-trap cleanup EXIT
+# default dokku domain setup (based on app name)
+  if [[ "$APP" == *.* ]] && [[ "$SUBDOMAIN" == "$APP" ]]; then
+    autohostname="${APP/\//-}"
+  else
+    autohostname="${APP/\//-}.$VHOST"
+  fi
 
-
-appvhost="${TMPDIR}/VHOST";
-if [[ -s "$appvhost" ]] ; then
-  cat "$appvhost" > ${TMPDIR}/SORTED;
-  userhostnames="${TMPDIR}/SORTED"
-else
-  exit 0;
-fi
-
+# get app root's VHOST file
+  docker cp $CONTAINERID:/app/VHOST $TMPDIR 2> /dev/null || true;
+  appvhost="${TMPDIR}/VHOST";
+  
+# exit if appvhost doesnt exist, or is empty
+  [[ ! -s "$appvhost" ]] && exit 0;
 
 # return regular stdout
-exec 1<&4
-# horrible spagetti pipes, needs some better scripting
+  exec 1<&4
+  
+# TODO: refactor
 # appends dokku generated hostname to user hostnames,               removes comments,     rm empty lines, lowercase,           unique lines
-printf "%s\n" "$autohostname" "$(cat $userhostnames 2> /dev/null)" | sed 's:^\s*#.*$::g' | grep -v '^$' | tr '[A-Z]' '[a-z]' | awk '!x[$0]++';
+  printf "%s\n" "$autohostname" "$(cat $appvhost 2> /dev/null)" | sed 's:^\s*#.*$::g' | grep -v '^$' | tr '[A-Z]' '[a-z]' | awk '!x[$0]++';
